package com.xik.aibookkeeping.pojo.vo;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.experimental.Accessors;

import java.io.Serial;
import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * <p>
 * 用户账单表
 * </p>
 *
 * @author panxikai
 * @since 2025-06-27
 */
@Data
@EqualsAndHashCode(callSuper = false)
@Accessors(chain = true)
public class BillUserVO implements Serializable {

    @Serial
    private static final long serialVersionUID = 1L;

    /**
     * 主键
     */
    private Long id;


    /**
     * 类型（revenue收入/expenditures支出/notRecorded不记入收支）
     */
    private String type;

    /**
     * 分类（餐饮、交通等）
     */
    private String category;

    /**
     * 金额
     */
    private BigDecimal amount;

    /**
     * 备注信息
     */
    private String remark;


    /**
     * 创建时间（默认现在）
     */
    private LocalDateTime createTime;

    /**
     * 修改时间（默认现在）
     */
    private LocalDateTime updateTime;


    /**
     * 是否AI自动生成
     */
    private Integer isAutoGenerated;

    /**
     * AI分类置信度(0-1)
     */
    private BigDecimal aiConfidence;

    /**
     * AI分析元数据
     */
    private String aiAnalysis;

    /**
     * 账单时间
     */
    private LocalDateTime billTime;



}
